# Generated by Django 6.0 on 2025-12-11 00:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Habit',
            new_name='Action',
        ),
        migrations.RenameModel(
            old_name='HabitEntry',
            new_name='MoodEntry',
        ),
    ]
